### ISSUE TITLE
UX Audit of 5 DApps

### ISSUE THREAD

**Issue by alegw** [alegw/status-design#1]
See https://github.com/status-im/design/issues/1.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x533dad578d9c7928d04ab885d976b5aacf18e8e4d1422333a703bb9296f82d1c](https://etherscan.io/tx/0x533dad578d9c7928d04ab885d976b5aacf18e8e4d1422333a703bb9296f82d1c)
