### ISSUE TITLE
Flow design of ‘Invite friends'

### ISSUE THREAD

**Issue by alegw** [alegw/status-design#2]
See https://github.com/status-im/design/issues/2.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3430693e999f0be321423d47a305cf268671e2166caa4d32cb11498a60f60ff8](https://etherscan.io/tx/0x3430693e999f0be321423d47a305cf268671e2166caa4d32cb11498a60f60ff8)
